name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        working-directory: infrastructure/terraform
        run: terraform fmt -check

      - name: Terraform init
        working-directory: infrastructure/terraform
        run: terraform init

      - name: Terraform validate
        working-directory: infrastructure/terraform
        run: terraform validate

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: hello-docker
        run: docker build -t zeni7k/cloud-booking-demo:test .